### ISSUE TITLE
Missing brainfuck implementation

### ISSUE THREAD

**Issue by Dfmaaa** [mawerty/Is-Prime#2]

**Comment by jeanlucaslima** [comment]
Are you gonna do it?

**Comment by carl010010** [comment]
`[-]`

"This C# code represents a function that always returns false, regardless of the input. Here's a corresponding Brainfuck program that sets the first memory cell to zero, which could be interpreted as "false" (since non-zero values are often considered "true"):

This Brainfuck code will set the current memory cell to zero, effectively representing "false". Keep in mind that Brainfuck does not have functions like in high-level languages, so the code may not be directly comparable to the C# function you provided."

- GPT-4

**Comment by mawerty** [comment]
I will do it in a few hours, i am little busy now.

**Comment by mawerty** [comment]
Added!
